/** @preserve @author Sandeep Wawdane @license MIT */
(function (root) {
'use strict';

const PAGE = { w: 595, h: 842, margin: 48 };
const CONTENT = { x: PAGE.margin, w: PAGE.w - 2 * PAGE.margin };
const MAX_Y = PAGE.h - PAGE.margin - 28;

const COLORS = {
    text:        [15, 20, 28],
    textMuted:   [95, 105, 120],
    textSubtle:  [155, 165, 180],
    border:      [222, 226, 232],
    accent:      [4, 120, 87],
    fail:        [190, 18, 60],
    review:      [180, 83, 9],
    info:        [14, 124, 177],
    pass:        [4, 120, 87],
    cardBg:      [245, 247, 250],
    bgAlt:       [238, 241, 246],
    high:        [190, 18, 60],
    critical:    [127, 29, 29],
    medium:      [180, 83, 9],
    low:         [14, 124, 177],
};

function toJsPDF() {
    const jspdfNs = root.jspdf || (typeof window !== 'undefined' ? window.jspdf : null);
    if (!jspdfNs || !jspdfNs.jsPDF) throw new Error('jsPDF library not loaded');
    return new jspdfNs.jsPDF({ unit: 'pt', format: 'a4', compress: true });
}

function severityColor(sev) {
    const s = (sev || '').toLowerCase();
    if (s === 'critical') return COLORS.critical;
    if (s === 'high' || s === 'fail') return COLORS.fail;
    if (s === 'medium' || s === 'warning' || s === 'review') return COLORS.review;
    if (s === 'low' || s === 'info') return COLORS.info;
    return COLORS.pass;
}

function statusBadge(status) {
    const s = (status || '').toLowerCase();
    if (s === 'pass')   return { label: 'PASS',   color: COLORS.pass };
    if (s === 'fail')   return { label: 'FAIL',   color: COLORS.fail };
    if (s === 'review') return { label: 'REVIEW', color: COLORS.review };
    if (s === 'error')  return { label: 'ERROR',  color: COLORS.textMuted };
    return { label: (status || 'UNKNOWN').toUpperCase(), color: COLORS.textMuted };
}

class PDF {
    constructor() {
        this.doc = toJsPDF();
        this.y = PAGE.margin;
        this.pageNo = 1;
        this.results = null;
    }
    setFont(family, style, size) {
        this.doc.setFont(family || 'helvetica', style || 'normal');
        if (size) this.doc.setFontSize(size);
    }
    ensure(h) { if (this.y + h > MAX_Y) this.addPage(); }
    addPage(skipHeader) {
        this.doc.addPage();
        this.pageNo++;
        this.y = PAGE.margin;
        if (!skipHeader) this.drawPageHeader();
    }
    drawPageHeader() {
        const d = this.doc;
        d.setFont('helvetica', 'normal'); d.setFontSize(8);
        d.setTextColor.apply(d, COLORS.textSubtle);
        const pkg = (this.results && this.results.package) || 'Report';
        d.text('ADB Auditor / ' + pkg, PAGE.margin, 28);
        d.text(String(this.pageNo), PAGE.w - PAGE.margin, 28, { align: 'right' });
        d.setDrawColor.apply(d, COLORS.border);
        d.setLineWidth(0.5);
        d.line(PAGE.margin, 34, PAGE.w - PAGE.margin, 34);
        this.y = PAGE.margin + 8;
    }
    drawFooter() {
        const d = this.doc;
        const tp = d.internal.getNumberOfPages();
        for (let i = 1; i <= tp; i++) {
            d.setPage(i);
            d.setFont('helvetica', 'normal'); d.setFontSize(7);
            d.setTextColor.apply(d, COLORS.textSubtle);
            d.text('Generated by ADB Auditor · ' + new Date().toISOString(), PAGE.margin, PAGE.h - 24);
            d.text('Page ' + i + ' of ' + tp, PAGE.w - PAGE.margin, PAGE.h - 24, { align: 'right' });
        }
    }
    text(str, opts) {
        const o = opts || {};
        const size = o.size || 10;
        const style = o.style || 'normal';
        const color = o.color || COLORS.text;
        const lineHeight = o.lineHeight || (size * 1.35);
        const x = o.x != null ? o.x : CONTENT.x;
        const maxW = o.maxW != null ? o.maxW : CONTENT.w;
        this.setFont('helvetica', style, size);
        this.doc.setTextColor.apply(this.doc, color);
        const text = String(str == null ? '' : str);
        const lines = this.doc.splitTextToSize(text, maxW);
        const totalH = lines.length * lineHeight;
        this.ensure(totalH);
        for (const ln of lines) {
            this.doc.text(ln, x, this.y + lineHeight - 3);
            this.y += lineHeight;
        }
        if (o.gap != null) this.y += o.gap;
    }
    mono(str, opts) {
        const o = Object.assign({}, opts || {});
        const size = o.size || 9;
        const lineHeight = o.lineHeight || (size * 1.4);
        const x = o.x != null ? o.x : CONTENT.x;
        const maxW = o.maxW != null ? o.maxW : CONTENT.w;
        this.setFont('courier', 'normal', size);
        this.doc.setTextColor.apply(this.doc, o.color || COLORS.textMuted);
        const text = String(str == null ? '' : str);
        const lines = this.doc.splitTextToSize(text, maxW);
        const totalH = lines.length * lineHeight + 8;
        this.ensure(totalH);
        if (o.bg !== false) {
            this.doc.setFillColor.apply(this.doc, COLORS.cardBg);
            this.doc.rect(x - 4, this.y, maxW + 8, totalH - 4, 'F');
        }
        this.y += 4;
        for (const ln of lines) {
            this.doc.text(ln, x, this.y + lineHeight - 3);
            this.y += lineHeight;
        }
        this.y += 4;
    }
    rule(opts) {
        const o = opts || {};
        const color = o.color || COLORS.border;
        const w = o.width || 0.5;
        this.ensure(o.gap || 8);
        this.doc.setDrawColor.apply(this.doc, color);
        this.doc.setLineWidth(w);
        this.doc.line(CONTENT.x, this.y, CONTENT.x + CONTENT.w, this.y);
        this.y += (o.gap || 8);
    }
    badge(label, color, x, y) {
        const d = this.doc;
        d.setFont('helvetica', 'bold', 8);
        const w = d.getTextWidth(label) + 12;
        d.setFillColor.apply(d, color);
        d.roundedRect(x, y - 9, w, 13, 3, 3, 'F');
        d.setTextColor(255, 255, 255);
        d.text(label, x + 6, y);
        return w;
    }
    cover() {
        const d = this.doc;
        const r = this.results || {};
        const sum = r.summary || { pass: 0, fail: 0, review: 0, error: 0 };
        d.setFillColor.apply(d, COLORS.accent);
        d.rect(0, 0, PAGE.w, 6, 'F');

        this.y = 110;
        this.setFont('helvetica', 'normal', 10);
        d.setTextColor.apply(d, COLORS.textMuted);
        d.text('SECURITY REPORT', PAGE.margin, this.y);
        this.y += 8;

        this.setFont('helvetica', 'bold', 28);
        d.setTextColor.apply(d, COLORS.text);
        d.text(r.package || 'Application', PAGE.margin, this.y + 24);
        this.y += 36;

        this.setFont('helvetica', 'normal', 10);
        d.setTextColor.apply(d, COLORS.textMuted);
        const meta = [];
        if (r.timestamp) meta.push('Scanned: ' + new Date(r.timestamp).toLocaleString());
        if (r.device && r.device.model) meta.push('Device: ' + r.device.model);
        if (r.device && r.device.android) meta.push('Android ' + r.device.android);
        if (r.device && r.device.serial) meta.push('Serial: ' + r.device.serial);
        d.text(meta.join('  ·  '), PAGE.margin, this.y);
        this.y += 28;

        const cardW = (CONTENT.w - 24) / 4;
        const cards = [
            { v: sum.pass   || 0, label: 'Pass',   color: COLORS.pass },
            { v: sum.fail   || 0, label: 'Fail',   color: COLORS.fail },
            { v: sum.review || 0, label: 'Review', color: COLORS.review },
            { v: sum.error  || 0, label: 'Error',  color: COLORS.textMuted },
        ];
        cards.forEach((c, i) => {
            const x = PAGE.margin + i * (cardW + 8);
            d.setFillColor.apply(d, COLORS.cardBg);
            d.roundedRect(x, this.y, cardW, 80, 6, 6, 'F');
            d.setDrawColor.apply(d, COLORS.border);
            d.setLineWidth(0.5);
            d.roundedRect(x, this.y, cardW, 80, 6, 6, 'S');
            d.setFont('helvetica', 'bold', 28);
            d.setTextColor.apply(d, c.color);
            d.text(String(c.v), x + cardW / 2, this.y + 38, { align: 'center' });
            d.setFont('helvetica', 'normal', 9);
            d.setTextColor.apply(d, COLORS.textMuted);
            d.text(c.label.toUpperCase(), x + cardW / 2, this.y + 62, { align: 'center' });
        });
        this.y += 100;

        this.text('Summary', { size: 14, style: 'bold' });
        const total = (sum.pass || 0) + (sum.fail || 0) + (sum.review || 0) + (sum.error || 0);
        const failPct = total > 0 ? Math.round(((sum.fail || 0) / total) * 100) : 0;
        const reviewPct = total > 0 ? Math.round(((sum.review || 0) / total) * 100) : 0;
        let verdict;
        if ((sum.fail || 0) > 0) verdict = 'Failures present. Review marked issues and apply recommended mitigations before release.';
        else if ((sum.review || 0) > 0) verdict = 'No outright failures, but review-marked items need manual verification.';
        else if ((sum.pass || 0) > 0) verdict = 'All executed checks passed against this build.';
        else verdict = 'No checks executed.';
        this.text(verdict, { color: COLORS.textMuted, gap: 8 });
        if (total > 0) {
            this.text(failPct + '% fail · ' + reviewPct + '% review · ' + (100 - failPct - reviewPct) + '% pass/error', { size: 9, color: COLORS.textSubtle });
        }
    }
    testSection(test) {
        const sb = statusBadge(test.status);
        this.ensure(60);
        const startY = this.y;
        const d = this.doc;

        d.setFillColor.apply(d, COLORS.cardBg);
        d.roundedRect(CONTENT.x, startY, CONTENT.w, 28, 4, 4, 'F');
        d.setDrawColor.apply(d, COLORS.border);
        d.setLineWidth(0.5);
        d.roundedRect(CONTENT.x, startY, CONTENT.w, 28, 4, 4, 'S');

        d.setFont('helvetica', 'bold', 11);
        d.setTextColor.apply(d, COLORS.text);
        d.text(test.title || test.id || '(test)', CONTENT.x + 8, startY + 18);

        this.badge(sb.label, sb.color, CONTENT.x + CONTENT.w - 64, startY + 18);
        this.y = startY + 36;

        if (test.id || test.category) {
            const parts = [];
            if (test.id) parts.push(test.id);
            if (test.category) parts.push(test.category);
            this.text(parts.join(' · '), { size: 8, color: COLORS.textSubtle, gap: 4 });
        }
        if (test.description) {
            this.text(test.description, { size: 9, color: COLORS.textMuted, gap: 6 });
        }
        if (test.error) {
            this.text('Error: ' + test.error, { size: 9, color: COLORS.fail, gap: 6 });
        }

        const findings = test.findings || [];
        if (findings.length === 0) {
            this.text('No findings.', { size: 9, color: COLORS.textSubtle, gap: 10 });
            return;
        }

        for (let i = 0; i < findings.length; i++) {
            this.findingItem(findings[i], i + 1);
        }
        this.y += 4;
    }
    findingItem(f, idx) {
        const d = this.doc;
        const sev = f.severity || (f.note ? 'info' : 'info');
        const sevColor = severityColor(sev);
        this.ensure(40);

        d.setDrawColor.apply(d, sevColor);
        d.setLineWidth(2);
        d.line(CONTENT.x, this.y, CONTENT.x, this.y + 12);

        d.setFont('helvetica', 'bold', 9);
        d.setTextColor.apply(d, COLORS.text);
        const head = '#' + idx + '  ' + (f.type || 'finding').replace(/_/g, ' ');
        d.text(head, CONTENT.x + 10, this.y + 9);

        if (f.severity) {
            const w = d.getTextWidth(head);
            this.badge(String(f.severity).toUpperCase(), sevColor, CONTENT.x + 14 + w, this.y + 10);
        }
        this.y += 14;

        if (f.note) this.text(f.note, { size: 9, x: CONTENT.x + 10, maxW: CONTENT.w - 10, color: COLORS.textMuted, gap: 4 });
        if (f.location) this.text('Location: ' + f.location, { size: 8, x: CONTENT.x + 10, maxW: CONTENT.w - 10, color: COLORS.textSubtle, gap: 2 });
        if (f.file) this.text('File: ' + f.file, { size: 8, x: CONTENT.x + 10, maxW: CONTENT.w - 10, color: COLORS.textSubtle, gap: 2 });
        if (f.dataType) this.text('Type: ' + f.dataType, { size: 8, x: CONTENT.x + 10, maxW: CONTENT.w - 10, color: COLORS.textSubtle, gap: 2 });
        if (f.count != null && f.count > 1) this.text('Occurrences: ' + f.count, { size: 8, x: CONTENT.x + 10, maxW: CONTENT.w - 10, color: COLORS.textSubtle, gap: 2 });

        if (f.evidence) {
            this.mono(String(f.evidence).slice(0, 1500), { x: CONTENT.x + 10, maxW: CONTENT.w - 10, size: 8 });
        }
        if (Array.isArray(f.components) && f.components.length > 0) {
            this.text('Components:', { size: 8, style: 'bold', x: CONTENT.x + 10, maxW: CONTENT.w - 10, color: COLORS.text, gap: 2 });
            for (const c of f.components.slice(0, 30)) {
                this.text('· ' + String(c).slice(0, 200), { size: 8, x: CONTENT.x + 16, maxW: CONTENT.w - 16, color: COLORS.textMuted, gap: 1 });
            }
            if (f.components.length > 30) this.text('… ' + (f.components.length - 30) + ' more', { size: 8, x: CONTENT.x + 16, color: COLORS.textSubtle, gap: 2 });
        }
        if (Array.isArray(f.instances) && f.instances.length > 0) {
            this.text('Instances (' + f.instances.length + '):', { size: 8, style: 'bold', x: CONTENT.x + 10, color: COLORS.text, gap: 2 });
            for (const inst of f.instances.slice(0, 50)) {
                const head = (inst.file ? inst.file : '') + (inst.line ? ':' + inst.line : '');
                if (head) this.text('· ' + head, { size: 8, x: CONTENT.x + 16, maxW: CONTENT.w - 16, color: COLORS.textMuted, gap: 1 });
                if (inst.match) this.mono(String(inst.match).slice(0, 300), { x: CONTENT.x + 16, maxW: CONTENT.w - 16, size: 8 });
                if (inst.line && typeof inst.line === 'string' && inst.line.length > 0 && !inst.match) this.mono(String(inst.line).slice(0, 300), { x: CONTENT.x + 16, maxW: CONTENT.w - 16, size: 8 });
            }
            if (f.instances.length > 50) this.text('… ' + (f.instances.length - 50) + ' more', { size: 8, x: CONTENT.x + 16, color: COLORS.textSubtle, gap: 2 });
        }
        if (f.recommendation) {
            this.text('Recommendation: ' + f.recommendation, { size: 8, x: CONTENT.x + 10, maxW: CONTENT.w - 10, style: 'italic', color: COLORS.accent, gap: 6 });
        }
        this.y += 4;
    }
    build(results) {
        this.results = results;
        this.cover();
        this.addPage();

        this.text('Findings', { size: 18, style: 'bold', gap: 10 });

        const tests = (results.tests || results.findings || []).slice();
        const order = { fail: 0, review: 1, pass: 2, error: 3 };
        tests.sort((a, b) => (order[a.status] || 9) - (order[b.status] || 9));
        for (const t of tests) {
            this.testSection(t);
        }
        if (tests.length === 0) {
            this.text('No tests in this scan.', { color: COLORS.textMuted });
        }
        this.drawFooter();
        return this.doc;
    }
}

function exportPDF(results, filenameBase) {
    const pdf = new PDF();
    const doc = pdf.build(results || {});
    const pkg = (results && results.package) || 'scan';
    const safe = String(pkg).replace(/[^A-Za-z0-9._-]/g, '_');
    const ts = new Date().toISOString().slice(0, 19).replace(/:/g, '-');
    doc.save((filenameBase || safe) + '_' + ts + '.pdf');
}

const api = { PDF, exportPDF };
if (typeof module !== 'undefined' && module.exports) module.exports = api;
else { root.ADBAuditorPDF = api; }

})(typeof self !== 'undefined' ? self : this);
